# Generated by Django 5.2.16 on 2026-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('biryani', 'Biryani'), ('pizza', 'Pizza / Burger'), ('noodles', 'FriedRice / Noodles'), ('starters', 'Starters'), ('beverages', 'beverages'), ('dessert', 'Desserts')], max_length=50)),
                ('image_path', models.CharField(help_text='ఉదాహరణకు: images/mc1.png', max_length=200)),
            ],
        ),
    ]
