# Generated by Django 5.2.16 on 2026-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_path',
            field=models.CharField(help_text='example: images/mc1.png', max_length=200),
        ),
    ]
