# Generated by Django 5.2.16 on 2026-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_menuitem_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('biryani', 'Biryani'), ('pizza', 'Pizza'), ('noodles', 'Noodles'), ('starters', 'Starters'), ('dessert', 'Dessert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
